name: Angel

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      plataform: ashure
      region: Peru
      cuenta: 123456
      clase: HDD

    steps:
      - name: Run a one-line script
        run: echo "Hello, mundo!"

      - name: Mensaje del Sabado 27
        run: echo "Curso de herramientas de desarrollo"

      - name: Variables del programa
        if: ${{env.plataform == 'ashure'}}
        run: |
             echo "La plataforma actual es: ${{ env.plataform }}"
             echo "La plataforma actual es: ${{ env.clase }}"
             echo "El repositorio es GITHUB_REPOSITORY"
